---
# Base playbook for cfme installation

#
# Dynamically create host groups based on distribution
#
- hosts: all
  tasks:
   - name: gather site specific fact data
     action: site_facts

   - name: group hosts by distribution
     action: group_by key={{ansible_distribution}}

#
# For RedHat hosts, register to RHN
#
- hosts: RedHat
  tasks:
   - include: tasks/rhn_register.yml
     when: rhn_method is defined

#
# For all other hosts, install CFME
#
- hosts: local

  vars:
     ovirt_cli_args: python files/ovirt-cli.py --url https://{{host_fqdn}}/api --username {{auth_user}} --password {{auth_pass}}

  tasks:
#   - include: tasks/yum_repos.yml
#
#   - name: install rhevm from rpm
#     yum: name=$item state=present
#     register: is_rhevm_rpm_installed
#     ignore_errors: yes
#     with_items: ['rhevm', 'rhevm-setup-plugin-allinone', 'rhevm-sdk', 'ovirt-engine-sdk', 'python-argparse']

   - include: tasks/rhevm_setup.yml

# TODO - If install from rpm was unsuccesful, try building it from upstream
# (refer to http://www.ovirt.org/Building_oVirt_engine)
#     when: is_rhevm_rpm_installed|failure

  handlers:
   - include: handlers/restart_services.yml
