---

- name: rhevm_import | enable non-interactive rhevm-image-uploader
  lineinfile: dest={{item}} state=present regexp='^passwd=' line='passwd={{auth_pass}}'
  with_items:
    - /etc/rhevm/imageuploader.conf
    - /etc/ovirt-engine/imageuploader.conf

- name: rhevm_import | download appliance
  get_url: url={{appliance_url}} dest=/tmp mode=0640
  register: appliance_file

- name: rhevm_import | determine image name
  shell: basename {{appliance_file|dest}} | sed 's|\.\w*$||'
  register: appliance_name

- name: rhevm_import | determine if template already imported
  shell: files/ovirt-cli.py --url https://{{host_fqdn}}/api --username {{auth_user}} --password {{auth_pass}} storagedomains.templates.list | grep {{appliance_name.stdout}}
  register: is_image_uploaded

- name: rhevm_import | rhevm-image-uploader
  shell: rhevm-image-uploader -v -e {{export_domain}} --name {{appliance_name.stdout}} upload {{appliance_file.dest}}
  when: is_image_uploaded|failed

- name: rhevm_import | wait for template upload to complete
  shell: MAX_TRIES=60 ; TRY=1 ; until files/ovirt-cli.py --url https://{{host_fqdn}}/api --username {{auth_user}} --password {{auth_pass}} storagedomains.templates.list | grep {{appliance_name.stdout}} ; do [ $TRY -gt $MAX_TRIES ] && exit 1 ; sleep 5; TRY=$((TRY+1)) ; done
  register: is_image_available

- name: rhevm_import | storagedomains.template.import
  shell: files/ovirt-cli.py --url https://{{host_fqdn}}/api --username {{auth_user}} --password {{auth_pass}} storagedomains.templates.import --name {{appliance_name.stdout}}
  when: is_image_available|success

## # Wait for template to be available
## TRY=1
## MAX_TRIES=60
## while [ -z $($OVIRT_CLI storagedomains.templates.list | grep $APPLIANCE_NAME) ]; do
##     rlLogInfo "Waiting for template '$APPLIANCE_NAME' to be available ($TRY) ..."
##     sleep 5
##     TRY=$((TRY+1))
##     # Fail if unable to reach success after MAX_TRIES attempts
##     if [ $TRY -gt $MAX_TRIES ]; then
##         rlFail "Unable to determine template '$APPLIANCE_NAME' activation"
##         rlRun "$OVIRT_CLI storagedomains.templates.list"
##         rlRun "$OVIRT_CLI templates.list"
##         break
##     fi
## done
##
## # Import template
## rlRun "$OVIRT_CLI storagedomains.templates.import --name $APPLIANCE_NAME" 0
